# Generated by Django 4.0.3 on 2022-04-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file2',
            field=models.FileField(blank=True, default='images/tpg.jpg', null=True, upload_to='profile/'),
        ),
    ]
