# Generated by Django 4.0.3 on 2022-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0004_alter_accured_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='accured',
            name='new_date',
            field=models.CharField(blank=-1, default=0, max_length=200, null=True),
        ),
    ]
