# Generated by Django 4.0.3 on 2022-04-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0005_accured_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accured',
            name='date',
            field=models.CharField(blank=-1, default=0, max_length=200, null=True),
        ),
    ]
