# Generated by Django 4.0.3 on 2022-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0007_alter_accured_date_alter_accured_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accured',
            name='date',
            field=models.DateTimeField(blank=-1, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='accured',
            name='new_date',
            field=models.DateTimeField(blank=-1, default=0, null=True),
        ),
    ]
