# Generated by Django 4.0.3 on 2022-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0008_alter_accured_date_alter_accured_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accured',
            name='date',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
