# Generated by Django 4.0.3 on 2022-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0013_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file2',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
