# Generated by Django 4.0.3 on 2022-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0019_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
