# Generated by Django 4.0.3 on 2022-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0020_profile_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to='webimg/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='webimg/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='webimg/'),
        ),
    ]
