# Generated by Django 4.0.3 on 2022-04-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0021_alter_profile_back_alter_profile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='back',
            field=models.FileField(blank=True, null=True, upload_to='webimg/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='webimg/'),
        ),
    ]
