# Generated by Django 4.0.4 on 2022-05-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0023_profile_num_refer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='num_refer',
        ),
    ]
