# Generated by Django 4.0.4 on 2022-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanapp', '0024_remove_profile_num_refer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refer_num',
            field=models.IntegerField(default=0),
        ),
    ]
